### ISSUE TITLE
PARTx logic adaption for XMESSAGGES

### ISSUE THREAD

**Issue by ByteProject** [daad-adventure-writer/MALUVA#10]
From ground up, DAAD has the logic of creating separate parts for a single adventure. What needs to be considered is that there could be multiple parts (DDBs) on disk (e.g. PART1 and PART2) that all want to make us of Xmessages, which is not possible in the current scenario / naming scheme of Xmessages. A solution could be that the name of the Xmessages lib could be defined as CondAct with your database. You would waste a word in VOC but would be very efficient having different parts with different Xmess databases.

**Comment by nataliapc** [comment]
A filename template for XMES files can be added to FILES1.BIN and FILES2.BIN, so you can open PART1 and PART2 with their own and differentiated XMES files.

**Comment by Utodev** [comment]
I'd like to find a solution that fits for all machines, but at this very
moment there are  already 3 different file name formats for xmessages
(0.XMB for ZX and MSX, nn.XMB for CPC, and just nn for c64).  Also, there
are many ways of loading the files games, there are at least 4 machines
that load the data in a different way cause they are different, and then
each author want to do this or that, and generates custom loaders to do so.
So althoug at the beginning I considered adding some POKE to the loaders
for part 2 and above, so at some the part being run is stored at some
specific address Maluva can check, I think it's complicated and user
unfriendly.

So I've come with this idea, comments are welcome:

New XMESINIT condact, with a parameter saying which part it is so:

- If 0 --> 0.XMB, nn.XBM and nn files are loader
- If 1 --> 1.XMB, mm.XMB and mm files are loaded, where mm is like nn plus
32, so first file is 32, second 33, etc. Maybe we can even use a round
number so users find it easier (50,51,52,53).

XMESINIT is not needed for part 1, but it is for part 2. We can even have
PART 3 o r PART 4 by adding 1 in case of ZX/MSX and 50 more each part in
CPC/C64.

I would also consider making XMB files start by 1.XBM or 01.XMB so for
MSX/ZX file number matches part. If I do that , I'd do th same for CPC and
C64 so firs file is 01.XMB or just 01 for C64.

Now that you are convinced (or not), I think it would be better to create a
XPART condact, so same idea can be used for graphichs or whatever the
future brings us. I'd have to think about it, casue fitting 2 games with
graphics in one side is in general not possible, unless you have few
images, but I think if I maje images for part 1 have the usual nnn.EXT
format, and image for part2 have the 2nnn.ext format, part3 3nnn.ext
format, etc.then it would not require much work from currentg authors.

**Comment by ByteProject** [comment]
I think the solution you're suggesting would work very well. Having the naming based on a CondAct was my initial suggestion too, a integer based CondAct as suggested in your case is likely the best way to do this. All you say is true so I agree on all topics. 

One thing I'd like to ask you to take into consideration though are dual system releases. As you said nobody would put two games on one disk, but what about two systems? For C64 I don't see a problem because the new Plus/4 interpreter shares all resources including images and XMES files with the C64 that is on the same disk. BUT: there could be the option having two adventures on one disk (or disc) on CPC & Spectrum +3. Level 9 did this a lot and it is absolutely possible. A CPC/+3 disk may hold 180k. That's enough for having a smaller adventure like my upcoming Rabenstein on one disk, even with both DDBs and even with all of the 19 images in both formats, assuming that an image takes up 1-3k depending on pixels and colours. Another thing to consider is maybe a text-only adventure dual system CPC/+3 that uses XMES. Ideal would be that the XMES database may be shared across the systems, or if that is not possible, that naming will work so that both files may co-exist on the same disk. 

This may or may not taken into consideration. When distributing digitally, it doesn't matter if you just create a new disk image, when distributing physically as well it makes a significant difference :) cheers!

**Comment by ByteProject** [comment]
PS: on the other hand you can of course just flip the disk (as 3" are always two sided) and get the same result, so you may just ignore my comment about dual systems. Please ignore it, two sides will work as well :D

**Comment by Utodev** [comment]
XMB files are not named the same between machines cause the limits of each
machine leads to use different file sizes. Those with  fseek use the ZX/MSX
approach (just one file). Those without fseek() use 2K files. Then having
2K files, means you can have up to 32 files, so instead of 0.XMB, you have
several nn.XMB (with two digitis). The reason to make the C64 files
extension-less is to avoid issue with PETSCII-> ASCII conversions.

Anyway, as you said, for +3/CPC you can just flip the disk if you want to
do dual release.

That reminds me of another challeng though: a game with too many locations
and a picture for them all can run out of directory entries in CPC/+3
easily (max 64 files per side). I suggested the game could ask the user to
flip disk when you go through some specific area in the game, or go back to
original area, so you can have some pictures in the other side. But then,
you would have to make a copy of the whole xmes database too, or Xmessage
will fail. It is still a solution, cause making two different sets of
Xmessages, one per side, is also too complicated.

**Comment by Utodev** [comment]
This has been resolved withe XPART condact

**Comment by Utodev** [comment]
with*
