### ISSUE TITLE
url typo at wiki (ww instead www)

### ISSUE THREAD

**Issue by Crispinophur** [daad-adventure-writer/MALUVA#12]
"Building C64 disks" wiki
https://github.com/daad-adventure-writer/MALUVA/wiki/Building-C64-disks
At "it's better if you start with these premade disks"
hyperlink is http://ww.ngpaws.com/downloads/DAAD/C64
it should be http://www.ngpaws.com/downloads/DAAD/C64

Cheers,
All the best!

**Comment by Utodev** [comment]
Also fixed this one, thanks!
