### ISSUE TITLE
1 sentence not translated (wiki)

### ISSUE THREAD

**Issue by Crispinophur** [daad-adventure-writer/MALUVA#13]
At 
https://github.com/daad-adventure-writer/MALUVA/wiki#function-0--xpicture
1st line is

> DRC soporta el condacto directamente:

I suppose it needs to be

> DRC supports condact directly:

(Srry to be nitpicking, just ur work is brilliant and I feel that it deserves to be perfect)

**Comment by Utodev** [comment]
Fixed, thanks!
