### ISSUE TITLE
MALUVA in MSX2 - fGFXFail system flag not working as expected

### ISSUE THREAD

**Issue by rogeriobiondi** [daad-adventure-writer/MALUVA#14]
Hello,

I'm implementing the Disk Swap feature for my game the following way:

```
#define fGFXFail            20

> _ _ 
XPICTURE    @fPicToLoad
GT          fGFXFail    127
MESSAGE     "#b       PLEASE CHANGE THE DISK AND PRESS ANY KEY.#n#n"
ANYKEY      
SKIP        -1
```

And seems that this function is not yet supported on Maluva for this platform.

Thank you very much.

**Comment by Utodev** [comment]
This seems to be a MSX2 related issue that, as commented somewhere else, is better to add to MSX2DAAD repo. I'm closing the issue.
