### ISSUE TITLE
Wiki mentions XSPLITSCREEN not XSPLITSCR

### ISSUE THREAD

**Issue by furroy** [daad-adventure-writer/MALUVA#15]
The Maluva wiki page mentions the command XSPLITSCREEN, but really it seems to be named XSPLITSCR in the DSF file. (I couldn't find a link to edit the wiki myself.)

**Comment by Utodev** [comment]
I have fixed that one and two more appearances of XSPLITSCREEN, as you mention, it should be XSPLITSCR.

Thank you @furroy .
